name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest tests.py

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Upload Flask Code to EC2
        run: |
          tar -czf flask-app.tar.gz server.py requirements.txt
          scp -o StrictHostKeyChecking=no flask-app.tar.gz ec2-user@${{ secrets.EC2_PUBLIC_IP }}:~/

      - name: Deploy Flask App on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            pkill -f server.py || true

            tar -xzf flask-app.tar.gz
            rm -f flask-app.tar.gz

            pip3 install --upgrade pip
            pip3 install -r requirements.txt

            nohup python3 server.py > flask.log 2>&1 &
          EOF

      - name: Delete SSH Key
        run: |
          rm -f ~/.ssh/id_rsa